### ISSUE TITLE
may cause auth error if password include letter $

### ISSUE THREAD

**Issue by calmzhu** [regclient/actions#18]
### Current Behavior

if password include special latter like $. will cause auth error. 

### Expected Behavior

My passowrd is 'abcd$e'. echo         echo "${{ inputs.password }}"  will got value "abcd' since $e is empty

**Comment by sudo-bmitch** [comment]
Thanks for the report! The latest update should resolve this. Let me know if you encounter any issues. I went a different direction than #19 because parsing the string inside the shell could still break with other characters like `'`.
